<h2> Controls Expired in 6 Monthes</h2>
	

 
<div class=" panel panel-default table-responsive">
<table  class="responsive">

<tr>
	<th> control number </th>
	<th> Product Name </th>
	<th> Product Type </th>
	<th> Expiry Date </th>
	<th> Batch No </th>
	<th> Customer </th>
	
	<th> Initial Ammount </th>
	<th> Balance </th>
	<th> Status </th>
	
</tr>


 
<?php foreach($this->controls as $control){
 ?>
<tr>
	
	<td> <?=$control->getControlNumber()?> </td>
	<td> <?=$control->getProductName()?> </td>
	<td> <?=$control->getProductType()->getName()?> </td>
	<td> <?=$control->getExpiryDate()->format('d/m/Y');?> </td>
	<td> <?=$control->getBatchNo() ?> </td>
	<td>  <?=$control->getCustomer()->getName()?> </td>
	<td>  <?=$control->getInitialAmmount()?> </td>
	<td> <?=$control->getBalance()?> </td>

	<td> <?=$control->getStatus()?> </td>
 
	<td> <a href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'showControl','id'=>$control->getId()))?>"> show Details </a> </td>

</tr>
<?php } ?>
</table>
</div>
</div>