<h3>Customers</h3>


<table>

<tr>
<th> Id</th>
<th> Customer Name</th>
<th> Code</th>
<th> Customer Address</th>
<th>  </th>

</tr>
 
<?php foreach($this->customers as $customer){?>
<tr>
	
<td> <?=$customer->getId()?> </td>
<td> <?=$customer->getName()?> </td>
<td> <?=$customer->getCode()?></td>
<td> <?=$customer->getAddress()?></td>
<td>
	
	<a href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'showCustomer','id'=>$customer->getId()))?>">Show Details</a>
</td>
</tr>
<?php } ?>
</table>
<div class="row">
<?php
echo $this->form()->render($form);
?>

</div>
