<h3>Customer Inventory</h3>
	<a href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'addControl','id'=>$this->customer->getId()))?>">Add  New Control</a>


<div>
 <label >Customer Id</label><span class="clr" ><?= $this->customer->getId()?></span><br/>
 <label >Customer Name</label><span class="clr" ><?=$this->customer->getName()?></span><br/>
 <label >Code</label><span class="clr" ><?=$this->customer->getCode()?></span><br/>
 
</div>
<div>

<?php echo $this->form()->render($this->filter_form); ?>
</div>

<table>

<tr>
	<th> control number </th>
	<th> Product Name </th>
	<th> Product Type </th>
	
 	<th> Initial Ammount </th>
	<th> Balance </th>
	<th> Controls Count </th>

	<th> Qurantine </th>
	<th> Released </th>
	<th> Rejected 	</th>
</tr>


 
<?php foreach($this->controls as $control){
  ?>
<tr>
 
	<td> <?=$control['code']?> </td>
	<td> <?=$control['product_name']?> </td>
	<td> <?=$control['product_type']?> </td>
 	<td>  <?=$control['initial_ammount']?> </td>
	<td> <?=$control['balance']?> </td>
	<td> <?=$control['control_count']?> </td>
	

	<td> <?=$control['quarntine']?> </td>
	<td> <?=$control['released']?> </td>
	<td> <?=$control['rejected']?> </td>
	<td> <a href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'showProduct','id'=>$control['product_code']))?>"> show Details </a> </td>

</tr>
<?php } ?>
</table>
