<h2><?=$this->controls[0]->getProductName()?>  Inventory  </h2>
	

<div>
	<a class="button-link "  href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'showCustomer', 'id'=>$this->controls[0]->getCustomer()->getId()))?>">Back</a>
	<a class="button-link "  href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'addControl','id'=>$this->controls[0]->getCustomer()->getId()), array('query'=>array('controlId'=>$this->controls[0]->getId())))?>">Add  New Control to <?=$this->controls[0]->getProductName()?> </a>
 
 
</div>
<br/>

<table>

<tr>
	<th> control number </th>
	<th> Product Name </th>
	<th> Product Type </th>
	<th> Expiry Date </th>
	<th> Batch No </th>
	
	<th> Initial Ammount </th>
	<th> Balance </th>

	<th> Status </th>
	
</tr>


 
<?php foreach($this->controls as $control){
 ?>
<tr>
	
	<td> <?=$control->getControlNumber()?> </td>
	<td> <?=$control->getProductName()?> </td>
	<td> <?=$control->getProductType()->getName()?> </td>
	<td> <?=$control->getExpiryDate()->format('d/m/Y');?> </td>
	<td> <?=$control->getBatchNo() ?> </td>
	
	<td>  <?=$control->getInitialAmmount()?> </td>
	<td> <?=$control->getBalance()?> </td>

	<td> <?=$control->getStatus()?> </td>
 
	<td> <a href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'showControl','id'=>$control->getId()))?>"> show Details </a> </td>

</tr>
<?php } ?>
</table>
