<h3>Customer Inventory</h3>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'addTransaction','id'=>$this->control->getId()))?>">Add  Out Transaction</a>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'addInTransaction','id'=>$this->control->getId()))?>">Add  In Transaction</a>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'editRetestDate','id'=>$this->control->getId()))?>">Edit Retest Date</a>
	
	<?php
	if($this->control->getBalance() >0 ){
	foreach($this->allowedActions[$this->control->getStatus()] as $action)	 {?>
		<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>$action['method'],'id'=>$this->control->getId()))?>">Move to <?=$action['label']?> </a>
	
	<?}
	}?>


<div class="control">
 <label >Control Number:</label> <span class="clr" ><?= $this->control->getControlNumber()?></span><br/>
 <label >Product Code:</label> <span class="clr" ><?=$this->control->getCode()?></span>
 <label >Control Name:</label> <span class="clr" ><?=$this->control->getProductName()?></span>
 <br/>
	 
 <label >Batch No. :</label> <span class="clr" ><?=$this->control->getBatchNo()?></span> 
 <label >Supplier/date :</label> <span class="clr" ><?=$this->control->getSupplier()?></span>
 <label >Unit :</label> <span class="clr" ><?=$this->control->getUnit()->getUnit()?></span>
 
 <br/>
 <label >Exp.date :</label> <span class="clr" ><?=$this->control->getExpiryDate()->format('d/m/y')?></span> 
 <label >Retest date :</label> <span class="clr" ><?=$this->control->getRetestDate() ? $this->control->getRetestDate()->format('d/m/y'): ''?></span> 
 <label >Manufacturing  date :</label> <span class="clr" ><?=$this->control->getManufacturingDate()->format('d/m/y')?></span> 
 
 <br/>
  
 <label >Balance :</label> <span class="clr" ><?=$this->control->getBalance()?></span> 
 <label >Status :</label> <span class="clr" ><?=$this->control->getStatus()?></span> 
 
 <br/>
 <label >Created By  :</label> <span class="clr" ><?=$this->control->getUser()->getUsername()?></span> 
 <label >Date Created  :</label> <span class="clr" ><?=$this->control->getDateCreated()->format('d/m/y')?></span> 
 


</div>


<table>

<tr>
	<th> In </th>
	<th> Out </th>
	<th> Balance </th>
	
	<th> description </th>
	<th> recipt No </th>
	<th> by  </th>
	<th> date </th>

</tr>


 
<?php foreach($this->control->getControlTransactionsList() as $trans){?>
<tr>
	
	<td> <?=$trans->getIn()?> </td>
	<td> <?=$trans->getOut()?> </td>
	<td> <?=$trans->getBalance()?> </td>
	<td> <?=$trans->getDescription()?> </td>
	<td> <?=$trans->getReceiptNo()?> </td>
	<td> <?=$trans->getUser()->getUsername();?> </td>
	<td> <?=$trans->getDateCreated()->format('d/m/Y');?> </td>
	
</tr>
<?php } ?>
</table>
