<h3>Customer Inventory</h3>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'addTransaction','id'=>$this->control->getId()))?>">Add  Out Transaction</a>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'addInTransaction','id'=>$this->control->getId()))?>">Add  In Transaction</a>
	<?php
	if ($this->control->getQuarntine()>0.0) {?>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'moveToReleased','id'=>$this->control->getId()))?>">Move to Released </a>
	<a class="button-link" href="<?=$this->url('application/default',array('controller'=>'Inventory','action'=>'moveToRejected','id'=>$this->control->getId()))?>">Move to Rejected </a>
	<?}?>


<div class="control">
 <label >Control Number:</label> <span class="clr" ><?= $this->control->getControlNumber()?></span><br/>
 <label >Product Code:</label> <span class="clr" ><?=$this->control->getCode()?></span>
 <label >Control Name:</label> <span class="clr" ><?=$this->control->getProductName()?></span>
 <br/>
	 
 <label >Batch No. :</label> <span class="clr" ><?=$this->control->getBatchNo()?></span> 
 <label >Exp.date :</label> <span class="clr" ><?=$this->control->getExpiryDate()->format('dd/mm/yyyy')?></span> 
 <label >Supplier/date :</label> <span class="clr" ><?=$this->control->getSupplier()?></span>
 <label >Unit :</label> <span class="clr" ><?=$this->control->getUnit()->getUnit()?></span>
 
 <br/>
 
 <label >Querntine :</label> <span class="clr" ><?=$this->control->getQuarntine()?></span> 
 <label >Released :</label> <span class="clr" ><?=$this->control->getReleased()?></span> 
 <label >Rejected :</label> <span class="clr" ><?=$this->control->getRejected()?></span><br/>


</div>


<table>

<tr>
	<th> In </th>
	<th> Out </th>
	<th> Balance </th>
	
	<th> description </th>
	<th> recipt No </th>
	<th> by  </th>
	<th> date </th>

</tr>


 
<?php foreach($this->control->getControlTransactionsList() as $trans){?>
<tr>
	
	<td> <?=$trans->getIn()?> </td>
	<td> <?=$trans->getOut()?> </td>
	<td> <?=$trans->getBalance()?> </td>
	<td> <?=$trans->getDescription()?> </td>
	<td> <?=$trans->getReceiptNo()?> </td>
	<td> <?=$trans->getUser()->getUsername();?> </td>
	<td> <?=$trans->getDateCreated()->format('d/m/Y');?> </td>
	
</tr>
<?php } ?>
</table>
