<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Inventory Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Inventory Application') ?></a>
                </div>
                <div class="navbar-header">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                         
                    </ul>
                </div><!--/.nav-collapse -->
                <div class="collapse navbar-collapse">
					<?php $this->partial('application/index/user',array()); ?>
					<div class="">
						<?php 
						if($user = $this->identity()) {
						 ?>
						<span style="float:right;color: #999999;"  class="username" >Welcome <a href="<?php echo $this->url('editProfile');?>"><span class="zf-green"><?php echo $this->escapeHtml($user->getUsername()); ?></span></a>()</span>
						<a href="<?php echo $this->url('logout');?>" class="btn btn-success btn-lg" style="float:right; margin-top: 25px"><?php echo $this->translate('Logout'); ?></a>
						<div style="clear: both"></div>


						<?php 
						}else{
						?>
							<span style="float:right;color: #999999;">Welcome <span  style="color: #FF8C00">Guest</span>!</span>
							<a href="<?php echo $this->url('login');?>" class="btn btn-success btn-lg" style="float:right; margin-top: 25px"><?php echo $this->translate('Login'); ?></a>
						<?php
						}
						?>
					</div>

				</div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy;   <?php echo date('Y') ?> by AG Technologies Ltd. <?php echo $this->translate('All rights reserved for ATCOpharma.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
