<div class="">ssssssssss
<?php 
if($user = $this->identity()) {
 ?>
<span style="float:right;color: #999999;"  >Welcome <a href="<?php echo $this->url('editProfile');?>"><span class="zf-green"><?php echo $this->escapeHtml($user->getUsername()); ?></span></a></span>
<a href="<?php echo $this->url('logout');?>" class="btn btn-success btn-lg" style="float:right; margin-top: 25px"><?php echo $this->translate('Logout'); ?></a>
<div style="clear: both"></div>


<?php 
}else{
?>
	<span style="float:right;color: #999999;">Welcome <span  style="color: #FF8C00">Guest</span>!</span>
	<a href="<?php echo $this->url('login');?>" class="btn btn-success btn-lg" style="float:right; margin-top: 25px"><?php echo $this->translate('Login'); ?></a>
<?php
}
?>
</div>
